---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: 8-demo-image-update-bb-app
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@example.com
        name: flux
    push:
      branch: main
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./clusters/staging
    strategy: Setters
