---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: 8-demo-image-policy-bb-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: 8-demo-image-repo-bb-app # reference the ImageRepository
  policy:
    semver:
      range: 7.8.x  # if there is a bump in the patch version, it's going to identify it and pull it as the latest tag.
