apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 30s
  path: ./apps/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system