# 
# Kustomization custom resource to load resource located in the apps folder
# 

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 30s
  path: ./infrastructure/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system